import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "var(--background, #f7f9fb)",
        foreground: "var(--foreground, #191c1e)",
        card: "var(--card, #ffffff)",
        "card-foreground": "var(--card-foreground, #191c1e)",
        popover: "var(--popover, #0c0d0f)",
        "popover-foreground": "var(--popover-foreground, #f8fafc)",
        primary: "#000000",
        "on-primary": "#ffffff",
        "primary-container": "#131b2e",
        "on-primary-container": "#7c839b",
        "primary-fixed": "#dae2fd",
        "on-primary-fixed": "#131b2e",
        "primary-fixed-dim": "#bec6e0",
        "on-primary-fixed-variant": "#3f465c",
        secondary: "#515f74",
        "on-secondary": "#ffffff",
        "secondary-container": "#d5e3fd",
        "on-secondary-container": "#57657b",
        "secondary-fixed": "#d5e3fd",
        "on-secondary-fixed": "#0d1c2f",
        "secondary-fixed-dim": "#b9c7e0",
        "on-secondary-fixed-variant": "#3a485c",
        tertiary: "#000000",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#00201d",
        "on-tertiary-container": "#0c9488",
        "tertiary-fixed": "#89f5e7",
        "on-tertiary-fixed": "#00201d",
        "tertiary-fixed-dim": "#6bd8cb",
        "on-tertiary-fixed-variant": "#005049",
        surface: "#f7f9fb",
        "on-surface": "#191c1e",
        "surface-bright": "#f7f9fb",
        "surface-dim": "#d8dadc",
        "surface-variant": "#e0e3e5",
        "on-surface-variant": "#45464d",
        "surface-tint": "#565e74",
        "surface-container": "#eceef0",
        "surface-container-low": "#f2f4f6",
        "surface-container-lowest": "#ffffff",
        "surface-container-high": "#e6e8ea",
        "surface-container-highest": "#e0e3e5",
        "on-background": "#191c1e",
        "inverse-surface": "#2d3133",
        "inverse-on-surface": "#eff1f3",
        "inverse-primary": "#bec6e0",
        outline: "#76777d",
        "outline-variant": "#c6c6cd",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        muted: "var(--muted, #17181c)",
        "muted-foreground": "var(--muted-foreground, #94a3b8)",
        accent: "var(--accent, #d97706)",
        "accent-foreground": "var(--accent-foreground, #ffffff)",
        destructive: "var(--destructive, #ef4444)",
        "destructive-foreground": "var(--destructive-foreground, #ffffff)",
        border: "var(--border, #18191e)",
        input: "var(--input, #18191e)",
        ring: "var(--ring, #f59e0b)",
      },
      spacing: {
        "stack-lg": "24px",
        "margin-desktop": "32px",
        "container-max": "1280px",
        "stack-md": "16px",
        gutter: "24px",
        "stack-sm": "8px",
        unit: "4px",
        "margin-mobile": "16px",
      },
      fontFamily: {
        geist: ["Geist", "sans-serif"],
        inter: ["Inter", "sans-serif"],
        display: ["Geist", "sans-serif"],
        "headline-lg": ["Geist", "sans-serif"],
        "headline-lg-mobile": ["Geist", "sans-serif"],
        "headline-md": ["Geist", "sans-serif"],
        "label-md": ["Geist", "sans-serif"],
        "label-sm": ["Geist", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
      },
      fontSize: {
        display: ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-lg-mobile": ["24px", { lineHeight: "1.2", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "1", letterSpacing: "0.01em", fontWeight: "500" }],
        "label-sm": ["12px", { lineHeight: "1", letterSpacing: "0.02em", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
};

export default config;
